dataset:
  type: kss
  root: /data/kss
experiment:
  optimizer: adamw
  init_lr: 1.0e-3
  weight_decay: 0.0
  betas: [0.5, 0.9]
  warmup:
    epoch: 5  # 5% of total epochs
    multiplier: 1
    buffer_epoch: 0
    min_lr: 1.0e-3
    mode: fix
    start_from_zero: True
  batch_size: 32
  epochs: 150
  save_ckpt_freq: 5
  test_freq: 1
